name: Check Translations
on:
  pull_request_target:
    types: [synchronize, opened]
    paths:
      - 'src/locales/**'

jobs:
  check_translations:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Install jq
        run: sudo apt install -y jq

      - name: Fetch repo
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          files: 'src/locales/*.json'

      - name: Run i18n-extract on changed locale files
        id: i18n-extract
        run: |
          mkdir ./i18n-extract

          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            locale=$(basename "$file" .json)
            languageFiles="./src/locales/${locale}.json"
            outputFile="./i18n-extract/${locale}.json"

            echo "::group::Extracting i18n data for locale: ${locale}"

            npx vue-i18n-extract \
              --vueFiles './src/**/{*.?(js|ts|vue),.i18nignore}' \
              --languageFiles "${languageFiles}" \
              --output "${outputFile}"

            echo "::endgroup::"
            
            MISSING=$(cat "${outputFile}" | jq '.missingKeys | length')
            UNUSED=$(cat "${outputFile}" | jq '.unusedKeys | length')

            echo "$file=|${file##*/}|${MISSING}|${UNUSED}|" >> $GITHUB_OUTPUT
          done

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            Language file analysis report:
            |File|Missing Keys|Unused Keys|
            |:---|---:|---:|
            ${{join(steps.i18n-extract.outputs.*, '
            ')}}
